### ISSUE TITLE
Running Purely on Python?

### ISSUE THREAD

**Issue by chase-watts** [LysanderGG/Simple-XMR-Miner#5]
Would is be possible to create a similar script that mined Monero but did it with just Python (without the need for C)?

**Comment by LysanderGG** [comment]
Yes it would be possible but bothersome.

**Comment by chase-watts** [comment]
It may be something that you want to consider looking into.  One of the reasons that NightMiner was so great was that it was able to running strictly on Python without additional dependencies.
