### ISSUE TITLE
Version 7 compatible?

### ISSUE THREAD

**Issue by miked63017** [LysanderGG/Simple-XMR-Miner#6]
Hi, thanks for this great example miner, it makes a lot more sense to me looking at the code in python(with a little bit of C) than it does to look at a pure C implementation. Helps me figure out how mining this actually works with less investigation required on my part. 

Will this setup in its current for work with the version 7 fork, or will there need to be adjustments in the code to make it work with version 7?

**Comment by miked63017** [comment]
BTW, this also works on OSX and raspberry pi with a few simple tweaks, though it is so slow on the pi that I cannot even get it to report the H/s lol. It is reasonably fast on OSX when comparing it to running on a linux machine. 

If you would like to support OSX I can submit a PR, just let me know...

**Comment by LysanderGG** [comment]
Hi, 

I am not sure for the version 7, we will probably have to update the C library.
I have not looked at it yet.

About the OSX version, I won't be able to test but if it is just some tweaks here and there, please do not hesitate to submit a PR!
