### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by 496080199** [LysanderGG/Simple-XMR-Miner#7]
Hi,please help.
It showed:
[2018-04-08 03:17:45] Mining Sate Error: Malformed job message
  {'jsonrpc': '2.0', 'method': 'job', 'params': {'blob': '0707e98ea6d605e47d81e6890149ebc73ddf4b2ee41357f5f7070a47fabf3434958cd0d254d276000000007f05872e016e177b9b5d474413e932b0f5d4ed693325998a8c7c5d86f644a55204', 'job_id': '8PCI9uu7Y8glm2dfL+YzYLqgAd4T', 'target': '0b4d0800', 'id': '00aed003-d28f-4f81-9675-b6aff00bf031'}

Why show this error?Is not support monero V7?

**Comment by LysanderGG** [comment]
The porting to monero v7 is not done yet.

**Comment by GovetaXV** [comment]
When will it be done? Please do it fast!
