### ISSUE TITLE
Error: Mining Sate Error: Malformed job message

### ISSUE THREAD

**Issue by GovetaXV** [LysanderGG/Simple-XMR-Miner#8]
I keep getting this error when trying to use the nicehash pool

**Comment by LysanderGG** [comment]
As you have probably seen in the other issue, this project has not integrated the new XMR algo (v7) yet.
https://github.com/LysanderGG/Simple-XMR-Miner/issues/7

Be sure to double check the intent of this project: https://github.com/LysanderGG/Simple-XMR-Miner/blob/master/README.md
It is for learning purpose, it is very slow compared to some other miners.
